function pickChannels(Physio)
%pickChannels: choose which mindware channels to use for what
%   sets fuzzy defaults (e.g. first with string matching 'ECG') to specific
%See also: Physio

chans_to_get = fieldnames(Physio.channel_names);

chans_in_raw = Physio.raw_data_tt.Properties.VariableNames;

for i=1:length(chans_to_get)
    chan = chans_to_get{i};
    prompt = {sprintf('Select  *** %s ***  channel:',upper(chan)), ...
        '(Click ''Default'' if no such channel, or unsure)'};
    [idx,tf] = listdlg( ...
        'ListString',chans_in_raw, ...
        'PromptString',prompt, ...
        'SelectionMode','single', ...
        'ListSize',[300,160], ...
        'CancelString','Default', ...
        'OKString','Use', ...
        'Name','Pick Channels');
    if(tf); Physio.channel_names.(chan)=chans_in_raw{idx}; end
end
end

